version: '3.9'
services:
  backend:
    build: ./
    container_name: backend
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - PORT=3001
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - HOSTNAME=db
      - DATABASE=questions_api
  db:
    image: mysql:8.0.27
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789